name: bedlam-minecraft-server

services:
  minecraft:
    image: bedlamtheatre/minecraft-server
    volumes:
      - type: volume
        source: minecraft-data
        target: /data
    ports:
      - "25565:25565" # Main
      - "25575:25575" # RCON
      - "19132:19132/udp" # Geyser
    environment:
      - "GITHUB_TOKEN=${GITHUB_TOKEN}"
      - "EULA=${EULA}"
    stdin_open: true
    tty: true
    pull_policy: never
    restart: unless-stopped
  data-server:
    image: rclone/rclone
    command: serve ftp /data --addr :80 --user=${RCLONE_USER:-anonymous} --pass=${RCLONE_PASS-""}
    volumes:
      - type: volume
        source: minecraft-data
        target: /data
    ports:
      - "9001:80"
    restart: unless-stopped
volumes:
  minecraft-data:
    name: minecraft-data
    external: true
